spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/sharewoodBootDB 
    url: jdbc:mysql://localhost:3306/sharewood_photos
    username: tomcatUser
    password: password1234
  jpa: 
    hibernate: 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  servlet: 
    multipart: 
      max-file-size: 10MB
      max-request-size: 10MB

server: 
  port: 8081
  servlet: 
    context-path: /sharewood

security:
  oauth2:
    client:
      client-id: Fleetwood
      client-secret: y471l12D2y55U5558rd2
    resource:
      id: SHAREWOOD           
      token-info-uri: http://localhost:8080/authorization/oauth/check_token        

check-token-endpoint-url: http://localhost:8080/authorization/oauth/check_token
               

# edit to match your own filesystem 
photos:
  baseDirPath: /home/dominique/workspace-sharewood-resource/photos/




